config/routes.rb
Cavintstone::Application.routes.draw do

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :articles
  resources :categories
  resources :portfolios, path: "works"
  resources :resumes
  resources :dynamic_contents
  resources :pages, except: :show
  get '/contact', to: 'contact_us/contacts#new', as: :contact_cavin
  get '/blog', to: 'articles#index', as: :blog
  get ':id', to: 'pages#show', as: :page

end

app/views/layouts/structure/_disqus-code.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'cavintstone'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/structure/_disqus-javascript.html.erb
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'cavintstone'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

app/views/layouts/structure/_footer-scripts.html.erb
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<!-- JavaScript -->
<%= javascript_include_tag "application" %>

app/views/layouts/structure/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="col-md-6">
      <p class="text-muted">&copy; <%= Time.now.year %> Cavin T. Stone  /  Dallas, Texas / <%= mail_to 'cavin@cavintstone.com' %> / <%= link_to('<i class="fa fa-github"></i> Github'.html_safe, 'http://github.com/cstone') %></p>
    </div>
    <div class="col-md-6 text-right">
      <p class="text-muted"> <%= link_to('<i class="fa fa-download"></i> Download my resume'.html_safe, "#{Resume.first.resume_pdf.url}") if Resume.first.resume_pdf %></p>
    </div>
  </div>
</div>

app/views/layouts/structure/_google-analytics.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-50011310-1', 'cavintstone.com');
    ga('send', 'pageview');

</script>

app/views/layouts/structure/_meta-scripts.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="../../assets/ico/favicon.ico">


<%= stylesheet_link_tag    "application", :media => "all" %>

<%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Font Awesome CSS -->
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<!-- Custom styles for this template -->
<%= stylesheet_link_tag 'mystyles' %>

<!-- Just for debugging purposes. Don't actually copy this line! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/structure/_nav.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Cavin T. Stone', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <li class="<%= cpa(page_path('about-me')) %>" ><%= link_to 'About Me', page_path('about-me') %></li>
        <li class="<%= cpa(page_path('skills')) %>"><%= link_to 'Skills', page_path('skills') %></li>
        <li class="<%= cpa(page_path('work-experience')) %>"><%= link_to 'Work Experience', page_path('work-experience') %></li>
        <li class="<%= cpa(page_path('resume')) %>"><%= link_to 'Resume', page_path('resume') %></li>
        <% if !@all_portfolio.empty?  %>
        <li class="<%= cpa(portfolios_path) %>"><%= link_to 'Portfolio', portfolios_path %></li>
        <% end %>
        <% if !@all_articles.empty? %>
        <li class="<%= cpa(blog_path) %>"><%= link_to 'Blog', blog_path %></li>
        <% end %>
        <li class="<%= cpa(contact_cavin_path) %>"><%= link_to 'Contact', contact_cavin_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>