config/routes.rb
Cavintstone::Application.routes.draw do

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :articles
  resources :categories
  resources :portfolios, path: "works"
  resources :resumes
  resources :dynamic_contents
  resources :pages, except: :show
  get '/contact', to: 'contact_us/contacts#new', as: :contact_cavin
  get '/blog', to: 'articles#index', as: :blog
  get ':id', to: 'pages#show', as: :page

end

app/models/dynamic_content.rb
class DynamicContent < ActiveRecord::Base
  attr_accessible :key, :title, :value

  def self.get_value key
    dynamic_content = DynamicContent.where(key: key).first
    return dynamic_content.value if !dynamic_content.nil?
    return "Value missing for key #{key}"
  end

  def self.get_title key
    dynamic_content = DynamicContent.where(key: key).first
    return dynamic_content.title if !dynamic_content.nil?
    return "Value missing for key #{key}"
  end

  def self.get_raw_value key
    DynamicContent.where(:key => key).first.try(:value)
  end
end

app/controllers/dynamic_contents_controller.rb
class DynamicContentsController < ApplicationController
  # GET /dynamic_contents
  # GET /dynamic_contents.json
  def index
    @dynamic_contents = DynamicContent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dynamic_contents }
    end
  end

  # GET /dynamic_contents/1
  # GET /dynamic_contents/1.json
  def show
    @dynamic_content = DynamicContent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dynamic_content }
    end
  end

  # GET /dynamic_contents/new
  # GET /dynamic_contents/new.json
  def new
    @dynamic_content = DynamicContent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dynamic_content }
    end
  end

  # GET /dynamic_contents/1/edit
  def edit
    @dynamic_content = DynamicContent.find(params[:id])
  end

  # POST /dynamic_contents
  # POST /dynamic_contents.json
  def create
    @dynamic_content = DynamicContent.new(params[:dynamic_content])

    respond_to do |format|
      if @dynamic_content.save
        format.html { redirect_to @dynamic_content, notice: 'Dynamic content was successfully created.' }
        format.json { render json: @dynamic_content, status: :created, location: @dynamic_content }
      else
        format.html { render action: "new" }
        format.json { render json: @dynamic_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dynamic_contents/1
  # PUT /dynamic_contents/1.json
  def update
    @dynamic_content = DynamicContent.find(params[:id])

    respond_to do |format|
      if @dynamic_content.update_attributes(params[:dynamic_content])
        format.html { redirect_to @dynamic_content, notice: 'Dynamic content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dynamic_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynamic_contents/1
  # DELETE /dynamic_contents/1.json
  def destroy
    @dynamic_content = DynamicContent.find(params[:id])
    @dynamic_content.destroy

    respond_to do |format|
      format.html { redirect_to dynamic_contents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dynamic_contents_helper.rb
module DynamicContentsHelper
end

app/views/dynamic_contents/_form.html.erb
<%= semantic_form_for @dynamic_content do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :key %>
    <%= f.input :value %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/dynamic_contents/edit.html.erb
<h1>Editing dynamic_content</h1>

<%= render 'form' %>

<%= link_to 'Show', @dynamic_content %> |
<%= link_to 'Back', dynamic_contents_path %>

app/views/dynamic_contents/index.html.erb
<h1>Listing dynamic_contents</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Key</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dynamic_contents.each do |dynamic_content| %>
  <tr>
    <td><%= dynamic_content.title %></td>
    <td><%= dynamic_content.key %></td>
    <td><%= dynamic_content.value %></td>
    <td><%= link_to 'Show', dynamic_content %></td>
    <td><%= link_to 'Edit', edit_dynamic_content_path(dynamic_content) %></td>
    <td><%= link_to 'Destroy', dynamic_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dynamic content', new_dynamic_content_path %>

app/views/dynamic_contents/new.html.erb
<h1>New dynamic_content</h1>

<%= render 'form' %>

<%= link_to 'Back', dynamic_contents_path %>

app/views/dynamic_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @dynamic_content.title %>
</p>

<p>
  <b>Key:</b>
  <%= @dynamic_content.key %>
</p>

<p>
  <b>Value:</b>
  <%= @dynamic_content.value %>
</p>


<%= link_to 'Edit', edit_dynamic_content_path(@dynamic_content) %> |
<%= link_to 'Back', dynamic_contents_path %>